name: Build ESP8266 Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile Sketch
        uses: armory/arduino-builder-action@v1
        with:
          board-fqbn: 'esp8266:esp8266:nodemcuv2'
          sketch-path: 'ZeroTwin.ino'

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: ZeroTwin-BIN
          path: build/*.bin
